import java.util.Random;

/**
 * Computes some statistics about families in which the parents decide
 * to have children until they have at least one child of each gender.
 * The program expects to get two command-line arguments: an int value
 * that determines how many families to simulate, and an int value
 * that serves as the seed of the random numbers generated by the program.
 * Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main(String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
		Random generator = new Random(seed);

		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		int sum = 0, m = 1, sumf1 = 0, sumf2 = 0, sumf4 = 0;
		double sumchild = 0, randomizer;
		boolean boy = false, girl = false;
		for (int i = 0; i < T; i++) {
			while (m == 1) {
				randomizer = generator.nextDouble();
				if (randomizer <= 0.5) {
					girl = true;
					sum++;
				} else {
					boy = true;
					sum++;
				}
				if (boy == true && girl == true)
					m = 0;
			}
			m = 1;
			sumchild += sum;
			boy = false;
			girl = false;
			if (sum == 2)
				sumf1++;
			else if (sum == 3)
				sumf2++;
			else
				sumf4++;
			sum = 0;
		}
		System.out.println("Average: " + sumchild / T + " children to get atleast one of each gender.");
		System.out.println("Number of families with 2 children: " + sumf1);
		System.out.println("Number of families with 3 children: " + sumf2);
		System.out.println("Number of families with 4 or more children: " + sumf4);
		Printer(sumf1, sumf2, sumf4);
	}

	public static void Printer(int sumf1, int sumf2, int sumf4) {
		if (sumf1 > sumf2)
			System.out.println("The most common number of children is 2.");
		else if (sumf2 > sumf1)
			System.out.println("The most common number of children is 3.");
		else if (sumf2 > sumf4)
			System.out.println("The most common number of children is 3.");
		else
			System.out.println("The most common number of children is 4 or more.");
	}
}
